package io.github.enkarin.chefbot.enums;

public enum ChatStatus {
    NEW_DISH_NAME,
    MAIN_MENU,
    NEW_DISH_SPICY,
    NEW_DISH_KITCHEN,
    NEW_DISH_FOODSTUFF,
    NEW_DISH_NEED_PUBLISH,
    NEW_DISH_TYPE,
    SELECT_DISH_SPICY,
    SELECT_DISH_KITCHEN,
    SELECT_DISH_PRICE,
    REMOVE_DISH,
    SELECT_DISH_TYPE,
    SELECT_DISH_PUBLISHED,
    APPROVE_BACK_TO_MAIN_MENU,
    EXECUTE_SEARCH,
    EXECUTE_SEARCH_RANDOM
}
