spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        default_schema: chefbot
        enable_lazy_load_no_trans: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chefdata
    username: chef
    password: ${DATABASE_PASS}
# todo telegram-bot:
#  todo name:
#  todo token: