spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chefdata
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
telegram-bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
adapter:
  prefix:
    approve: Одобрить
    decline: Отклонить