spring:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chefdata
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
# todo telegram-bot:
#  todo name:
#  todo token: